//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Class
    {
        public T_Class()
        {
            this.T_Student = new HashSet<T_Student>();
            this.T_Teacher = new HashSet<T_Teacher>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<T_Student> T_Student { get; set; }
        public virtual ICollection<T_Teacher> T_Teacher { get; set; }
    }
}
